"""added image column to categories

Revision ID: 29d30ff01996
Revises: e95f8a48fcc3
Create Date: 2021-08-13 05:00:29.846568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d30ff01996'
down_revision = 'e95f8a48fcc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish_category', sa.Column('image', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish_category', 'image')
    # ### end Alembic commands ###
