"""added a price column

Revision ID: c614e5ab84b2
Revises: 29d30ff01996
Create Date: 2021-08-13 06:07:38.228469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c614e5ab84b2'
down_revision = '29d30ff01996'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dish', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dish', 'price')
    # ### end Alembic commands ###
